name: new_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - django=5.1.6
  - djangorestframework=3.15.2
  - sqlite
  - pip
  - pip:
      - drf-yasg==1.21.8
      - django-cors-headers
      - djangorestframework-simplejwt
      - requests==2.31.0
      - PyYAML==6.0.1
      - sqlparse==0.5.3
      - pytz==2025.1
      - uritemplate==4.1.1
      - urllib3==2.3.0
      - pillow==11.1.0
      
